---
#
# Restart local network
#

- name: Restart network service
  hosts: all
  become: yes
  tasks:
    - name: Restart network
      service: 
        name: network
        state: restarted
        sleep: 3
...
